name: CI & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm prisma generate
      - run: pnpm build

  docker-build:
    runs-on: ubuntu-latest
    needs: build-app

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t pokedex-app:latest .

  deploy:
    runs-on: self-hosted
    needs: docker-build

    steps:
      - name: Deploy latest master
        run: |
          cd ~/projects/pokedex
          git fetch origin master
          git reset --hard origin/master
          docker compose up -d --build